version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: micro_erp_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: micro_erp_db
      POSTGRES_USER: erpuser
      POSTGRES_PASSWORD: erppassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
